dist: trusty
language: node_js
node_js:
  - "8"
addons:
  chrome: stable
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &